In [ ]:
import numpy as np

#float datatype
a=np.ones((5,5))
print('ones:\n',a)

y=np.zeros((3,3))# only permitted values in the matrix are True and False,initial matrix is zero matrix
print('zeros:\n',y)

b=np.zeros((3,3),dtype=bool)# only permitted values in the matrix are True and False,initial matrix is zero matrix
print('zeros:\n',b)

c=np.array([[1,2,3],[4,5,6]])
print('array:\n',c)

x=np.array([[1],[2],[3],[4],[5],[6]])
print('array:\n',x,'shape:',x.shape)

d=np.arange(20)#1D array
print('1D-arange:',d)

e=np.arange(0,101,10)# 3 rd parameter stands for step size , default =1
print('arange with spacing of 10 elements:',e)


#Ending element is inclusive
f=np.linspace(0,100,11)# 3rd parameter stands for number of elements
print('linspace:',f)

f=np.linspace(0,100,12,dtype=int)# 3rd parameter stands for number of elements , default - float
print('linspace:',f)

# Floating point values
g=np.random.random((2,2,2))
print('random:\n',g)

print('type\n')
print(type(a),type(b),type(c),type(d),type(e),type(f),type(g))

print('shape\n')
print(a.shape,b.shape,c.shape,d.shape,e.shape,f.shape,g.shape)

emp=np.empty((3,3,4))
print('empty:\n',emp)

ful=np.full((2,5),10)
print('full:\n',ful)

iden=np.identity(5)
print('identity:\n',iden)

print(a.dtype,b.dtype,c.dtype,d.dtype,e.dtype,f.dtype,g.dtype,emp.dtype,ful.dtype,iden.dtype)


ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zeros:
 [[False False False]
 [False False False]
 [False False False]]
array:
 [[1 2 3]
 [4 5 6]]
array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] shape: (6, 1)
1D-arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arange with spacing of 10 elements: [  0  10  20  30  40  50  60  70  80  90 100]
linspace: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
linspace: [  0   9  18  27  36  45  54  63  72  81  90 100]
random:
 [[[0.13612775 0.07959092]
  [0.268575   0.5279469 ]]

 [[0.84985141 0.04035009]
  [0.67835352 0.65688554]]]
type

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
shape

(5, 5) (3, 3) (2, 3) (20,) (11,) (12,) (2, 2, 2)
empty:
 [[[1.         1.         0.8        1.        ]
  [1.         0.9294

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape,len(a),a.ndim)

#gives no. of rows along x-axis
print(np.size(a, 0))

#gives no. of columns along y-axis
print(np.size(a, 1))

b=np.ones((2,3))
print(b.dtype)
temp = b.astype(int)
print(temp.dtype)

(2, 3) 2 2
2
3
float64
int64


In [ ]:
arr = np.array([[1.0,0,2],[0,1,0],[0,0,1]])
arr1 = np.array([[1.0,0,3],[0,1,0],[0,0,1]])

print('multiply scalar:\n',10*arr)
print('add:\n',arr+arr1)
print('element wise mult:\n',arr*arr1)#Element by element
print('reciprocal:\n',1/arr)

print('add:\n',np.add(arr,arr1))
print('subtract:\n',np.subtract(arr,arr1))
print('multiply:\n',np.multiply(arr,arr1))
print('division:\n',np.divide(arr,arr1))


multiply scalar:
 [[10.  0. 20.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]
add:
 [[2. 0. 5.]
 [0. 2. 0.]
 [0. 0. 2.]]
element wise mult:
 [[1. 0. 6.]
 [0. 1. 0.]
 [0. 0. 1.]]
reciprocal:
 [[1.  inf 0.5]
 [inf 1.  inf]
 [inf inf 1. ]]
add:
 [[2. 0. 5.]
 [0. 2. 0.]
 [0. 0. 2.]]
subtract:
 [[ 0.  0. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
multiply:
 [[1. 0. 6.]
 [0. 1. 0.]
 [0. 0. 1.]]
division:
 [[1.                nan 0.66666667]
 [       nan 1.                nan]
 [       nan        nan 1.        ]]


<ipython-input-20-f25e72494c22>:7: RuntimeWarning: divide by zero encountered in divide
  print('reciprocal:\n',1/arr)
<ipython-input-20-f25e72494c22>:12: RuntimeWarning: invalid value encountered in divide
  print('division:\n',np.divide(arr,arr1))


In [ ]:
# DOT for n dim array does matrix multiplication
# DOT for 1 dim array does dot product
# numpy class , methof

a=np.array([1,2,3])
print('exp:',np.exp(a))
print('sqrt:',np.sqrt(a))
print('log:',np.log(a))
print('sin:',np.sin(a))


arr = np.array([[1.0,0,2],[0,1,0],[0,0,1]])
arr1 = np.array([[1.0,0,3],[0,1,0],[0,0,1]])

print(np.dot(a,arr))# Row by Row dot product when matrix dimensions don't match


exp: [ 2.71828183  7.3890561  20.08553692]
sqrt: [1.         1.41421356 1.73205081]
log: [0.         0.69314718 1.09861229]
sin: [0.84147098 0.90929743 0.14112001]
[1. 2. 5.]


In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
#print(np.concatenate((a, b.T), axis=0))
#Throws Error
#all the input array dimensions for the concatenation axis must match exactly,
# but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1
print(np.concatenate((a, b.T), axis=1))
# array([[1, 2, 5],
#        [3, 4, 6]])
print(np.concatenate((a, b), axis=None))
# array([1, 2, 3, 4, 5, 6])

[[1 2]
 [3 4]
 [5 6]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
a=np.array([[1,2,3],[2,3,4]])
print(a,a.shape)
i = np.transpose(a) #Takes transpose
print(i,i.shape)

[[1 2 3]
 [2 3 4]] (2, 3)
[[1 2]
 [2 3]
 [3 4]] (3, 2)


In [ ]:
b=a.ravel() #Flatten the array - Doesn't work on the function , creates a new array
print(a)
print(b)
c=a.reshape(3, 2) #Reshape, but don’t change data
print(a)
print(c)

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]
[[1 2 3]
 [2 3 4]]
[[1 2]
 [3 2]
 [3 4]]


In [ ]:
# # iloc doesn't include last element , loc does
a=np.array([[1,2,3],[2,3,4]])
print('a:\n',a)
e=a.resize((3,2)) #Return a new array with shape(2,6) - Inplace return!!!
print('a:\n',a)
print('e:\n',e)# None
b=np.insert(a,3,5)  #Insert items in an array
print('a:\n',a)
print('b:\n',b)
c=np.delete(a,1)  #Delete items from an array
print('a:\n',a)
print('c:\n',c)

a:
 [[1 2 3]
 [2 3 4]]
a:
 [[1 2]
 [3 2]
 [3 4]]
e:
 None
a:
 [[1 2]
 [3 2]
 [3 4]]
b:
 [1 2 3 5 2 3 4]
a:
 [[1 2]
 [3 2]
 [3 4]]
c:
 [1 3 2 3 4]


In [14]:
#mean
a = np.array([[1,8,3], [7,5,6]])
print('mean of all the elemenets:',np.mean(a))# Will give the mean of all the elemenets
print('mean of elements along column:',np.mean(a, axis=0))# Will give the mean of elements along a column
print('mean of elements along a row:',np.mean(a, axis=1))# WIll give the mean of elements along a row

#sum
#Similar to mean
print('sum:',np.sum([0.5,0.5,0.5,1.5], dtype=np.int32,initial = 100))# first converted to int data type then added , with initial value of 100

#min and max
print('min:',np.min(a,axis=1, keepdims = True),'\nmax:',np.max(a))
#keepdims function will force the output to have the same dimensions as the input array.

# to find the Index of the Minimum Value Column-Wise
print('argmin:',np.argmin(a, axis=0))


mean of all the elemenets: 5.0
mean of elements along a row: [4.  6.5 4.5]
mean of elements along a column: [4. 6.]
sum: 101
min: [[1]
 [5]] 
max: 8
argmin: [0 1 0]


In [17]:
#random
print(np.random.randint(5, size=(2,3)))
print(np.random.randint(1, [4, 5, 20]))# 1 x 3 array with 3  upper bounds
print(np.random.randint([1, 5, 6],10))# 1 x 3 array with 3 lower  bounds

print(np.random.randn())# Returns a sample (or samples) from the “standard normal” distribution

[[4 2 1]
 [3 2 4]]
[ 3  4 17]
[1 6 6]
-1.696422580459484
